"""
Complement the sequences below and then transcribe the complement into RNA.
"""

seq1 = 'ATGCATGCTAGCTAGTCGATGCTTATTACGTAGCGGGTAACAAACGTACGCCATGCTATTGTCAGTGTGGGGGGATA'
seq2 = 'ATGCGATGCTAGCTTTACGTAGAGAGACTCCCCCGATAGATCGATCAGGATCGATTTTAGCTAGTCGA'
seq3 = 'ATCGCTAGCTGGGGGCATTAAACGTATCGATCCTACCTAGCTGACTGAXTCGATCGTATACGATGCTGTGACTG'
