"""
Do the following sequences of DNA contain the pieces given after them?
If so, how many times?
Then, count in total how many times A, T, C, G occur.
"""

### 1

sequence_1 = """AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGT
	GGATTAAAAAAAGAGTGTCTGATAGCAGCAGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCACGATGTCGGATCGTAT
	GCTAGTCAGTGTGTTTTTTTTAAAAGCAGGCTGCATGCTGTGTGTGTGTACGTATATGAAAAAATCAGC"""

piece_1_1 = 'GCA'
piece_1_2 = 'ATT'
piece_1_3 = 'TCA'
piece_1_4 = 'GCAAATCC'
